### ISSUE TITLE
Dataset Downloading

### ISSUE THREAD

**Issue by cyy280113999** [naver-ai/relabel_imagenet#11]
Could you provide another source of relabeled-dataset?  Dropbox really annoys me when it breaks.

**Comment by hellbell** [comment]
Sorry for your inconvenience. Would google drive be a good alternative?

**Comment by cyy280113999** [comment]
Really Thanks, I can make a try.

**Comment by hellbell** [comment]
https://drive.google.com/file/d/1iPzdlSRpNVOIvs0msHBfMWzHq2SFk3SE/view?usp=sharing

hope it works!

**Comment by cyy280113999** [comment]
Nice! Downloading continues from where it pause.
I saw your updating, Thank you
