### ISSUE TITLE
Crop Coordinate Calculation.

### ISSUE THREAD

**Issue by cyy280113999** [naver-ai/relabel_imagenet#13]
paragraph
```
def get_relabel(label_maps, batch_coords, num_batches):
    target_relabel = roi_align(
        input=label_maps,
        boxes=torch.cat(
            [torch.arange(num_batches).view(num_batches,
                                            1).float().cuda(),
             batch_coords.float() * label_maps.size(3) - 0.5], 1),
        output_size=(1, 1))
    target_relabel = torch.nn.functional.softmax(target_relabel.squeeze(), 1)
    return target_relabel
```
line
`batch_coords.float() * label_maps.size(3) - 0.5`
batch_coords is given by percentage [x0,y0,x1,y1],
and it recovers to region [0,15].
why coords is substracted by 0.5?

**Comment by hellbell** [comment]
As following the roi_align documentation (https://pytorch.org/vision/main/generated/torchvision.ops.roi_align.html),
we set `aligned=False`, so -0.5 for a better alignment.
