### ISSUE TITLE
LabelPooling in 4.3 Multi-Label Classification

### ISSUE THREAD

**Issue by mymuli** [naver-ai/relabel_imagenet#2]
Thank you very much for your meaningful research work!

For 4.3 **Multi-Label Classification**,  I would like to ask where is the code for **LabelPooling**?

**Comment by hellbell** [comment]
@mymuli Thank you for having an interest in our work!
First, code for `multi-label classification` is not provided in this repository.
Code for **LabelPooling** is here with `roialign` function,
https://github.com/naver-ai/relabel_imagenet/blob/main/utils/relabel_functions.py#L30-L39
