### ISSUE TITLE
about dataset download 

### ISSUE THREAD

**Issue by ziziyaziziya** [naver-ai/relabel_imagenet#7]
https://www.dropbox.com/s/9sxigpec7fxq8wh/relabel_imagenet.tar?dl=0 여기 링크에서  데이터 다운로드 계속 실패인데..혹시 다른 방법 더 있을가여??

**Comment by hellbell** [comment]
용량이 커서 다른 방법으로는 공유가 어려울 것 같습니다 
다운로드 링크는 접속이 잘 되시나요?

**Comment by ziziyaziziya** [comment]
다운로드 링크 접속은 잘 되요. 11G 까지는 다운로드 문제 없는데 마지막 1g에서 실패를 수십번 해서...뭔 문젠지 모르겠네요.
